<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="PREETISH" name="RetryMultipleFailedTest" tests="9" failures="2" timestamp="22 Apr 2018 11:43:16 GMT" time="0.113" errors="0">
  <testcase name="Test1" time="0.021" classname="retryfailedtesttorunagain.MyTest">
    <skipped/>
  </testcase> <!-- Test1 -->
  <testcase name="Test1" time="0.004" classname="retryfailedtesttorunagain.MyTest">
    <skipped/>
  </testcase> <!-- Test1 -->
  <testcase name="Test1" time="0.001" classname="retryfailedtesttorunagain.MyTest">
    <skipped/>
  </testcase> <!-- Test1 -->
  <testcase name="Test1" time="0.001" classname="retryfailedtesttorunagain.MyTest">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at retryfailedtesttorunagain.MyTest.Test1(MyTest.java:16)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- Test1 -->
  <testcase name="Test2" time="0.001" classname="retryfailedtesttorunagain.MyTest">
    <skipped/>
  </testcase> <!-- Test2 -->
  <testcase name="Test2" time="0.003" classname="retryfailedtesttorunagain.MyTest">
    <skipped/>
  </testcase> <!-- Test2 -->
  <testcase name="Test2" time="0.001" classname="retryfailedtesttorunagain.MyTest">
    <skipped/>
  </testcase> <!-- Test2 -->
  <testcase name="Test2" time="0.005" classname="retryfailedtesttorunagain.MyTest">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at retryfailedtesttorunagain.MyTest.Test2(MyTest.java:22)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- Test2 -->
  <testcase name="Test3" time="0.007" classname="retryfailedtesttorunagain.MyTest"/>
</testsuite> <!-- RetryMultipleFailedTest -->
